package com.example.plazapalm.networkcalls

enum class ApiEnums {
    LOGIN,
    SIGNUP,
    VERIFY_OTP,
    RESEND_OTP,
    DELETE_ACCOUNT,
    CHANGE_PASSWORD,
    CONTACT_US,
    UPDATE_EMAIL,
    LOG_OUT,
    FORGOT_PASS,
    GET_PROFILE,
    UPDATE_PROFILE,
    UPLOAD_IMAGES,
    GET_CATEGORIES,
    VALIDATE_OTP_UPDATE_EMAIL,
    GET_PREMIUM_STATUS,
    LIKES_DISLIKES,
    SAVE_POST_PROFILE,
    VALIDATE_USERNAME,
    GETPROFILE_BYCATE,
    GET_FAVDETAILS,
    ADD_TO_FAV,
    GET_POST_PROFILE,
    DELETE_POST,
    UPDATE_POST_PROFILE


}
